### ISSUE TITLE
`neptune-notebooks` does not work with `jupyterlab>=4.0`

### ISSUE THREAD

**Issue by GuangShuaiWang** [neptune-ai/neptune-notebooks#175] opened 2023-07-03 11:07 UTC
when I use nuptune-notebook in Jupyter-lab , I find this warning:
```
[W 2023-07-03 18:29:18.653 LabApp] The extension "neptune-notebooks" is outdated.
```
but it not come out in jupyter notebook, why? could you help me answer this question.

**Comment by SiddhantSadangi** [comment] 2023-07-03 11:15
Hello @GuangShuaiWang 👋 

Thank you for reporting this issue! Could you please provide us with more details:

**1.  Describe the bug**
﻿A clear and concise description of what is the problem you're experiencing. ﻿

**2. Reproduction**
﻿In as much detail as possible, please provide steps to reproduce the issue or code snippet.

﻿**3. Expected behavior**
﻿A clear and concise description of what you expected to happen.﻿

**4. Traceback**
﻿If applicable, add traceback or log output/screenshots to help explain your problem.

﻿**5. Environment info**
﻿The output of `pip list`:
The operating system you're using:
The output of `python --version`:

﻿﻿**6. Additional context**
﻿Add any other context about the problem here.

**Comment by GuangShuaiWang** [comment] 2023-07-03 11:33
ok, thanks @SiddhantSadangi, here are my description:

I want to use "neptune-notebooks" extension for Jupyter Lab and Jupyter notebook, so I follow this documents [1](https://docs.neptune.ai/tools/jupyter/overview/) [2](https://docs.neptune.ai/tools/jupyter/installing_extension/#__tabbed_2_1) to install it.

In Jupyter notebook, there are no problems, I can find "Upload", "Download","Archive" buttons.

but in Jupyter lab, it does't work, I can't find this buttons, and I find the output `[W 2023-07-03 18:29:18.653 LabApp] The extension "neptune-notebooks" is outdated.` Here are the detail:
```
(torch) WGS:~ wangguangshuai$ jupyter lab
[I 2023-07-03 18:29:14.771 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-07-03 18:29:14.782 ServerApp] Package jupyter_lsp took 0.0107s to import
[W 2023-07-03 18:29:14.782 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-07-03 18:29:14.786 ServerApp] Package jupyter_server_terminals took 0.0043s to import
[I 2023-07-03 18:29:14.787 ServerApp] Package nbclassic took 0.0004s to import
[W 2023-07-03 18:29:14.787 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-07-03 18:29:14.788 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-07-03 18:29:14.788 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-07-03 18:29:14.788 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-07-03 18:29:14.790 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-07-03 18:29:14.791 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-07-03 18:29:14.793 ServerApp] nbclassic | extension was successfully linked.
[W 2023-07-03 18:29:14.967 ServerApp] jupyter_nbextensions_configurator | error adding extension (enabled: True): The module 'jupyter_nbextensions_configurator' could not be found (No module named 'jupyter_nbextensions_configurator'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/wangguangshuai/miniforge3/envs/torch/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/wangguangshuai/miniforge3/envs/torch/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/wangguangshuai/miniforge3/envs/torch/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupyter_nbextensions_configurator' could not be found (No module named 'jupyter_nbextensions_configurator'). Are you sure the extension is installed?
[I 2023-07-03 18:29:14.967 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-07-03 18:29:15.018 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-07-03 18:29:15.019 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-07-03 18:29:15.019 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-07-03 18:29:15.020 LabApp] JupyterLab extension loaded from /Users/wangguangshuai/miniforge3/envs/torch/lib/python3.11/site-packages/jupyterlab
[I 2023-07-03 18:29:15.020 LabApp] JupyterLab application directory is /Users/wangguangshuai/miniforge3/envs/torch/share/jupyter/lab
[I 2023-07-03 18:29:15.020 LabApp] Extension Manager is 'pypi'.
[I 2023-07-03 18:29:15.021 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-07-03 18:29:15.023 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-07-03 18:29:15.024 ServerApp] notebooks 运行所在的本地路径: /Users/wangguangshuai
[I 2023-07-03 18:29:15.024 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-07-03 18:29:15.024 ServerApp] http://localhost:8888/lab?token=ee9b275d963c5e19632a926bd8117683f5fa36d050152ae2
[I 2023-07-03 18:29:15.024 ServerApp]     http://127.0.0.1:8888/lab?token=ee9b275d963c5e19632a926bd8117683f5fa36d050152ae2
[I 2023-07-03 18:29:15.024 ServerApp] 使用 Control-C 停止此服务器并关闭所有内核（连续操作两次便可跳过确认界面）。
[C 2023-07-03 18:29:15.026 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/wangguangshuai/Library/Jupyter/runtime/jpserver-50785-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=ee9b275d963c5e19632a926bd8117683f5fa36d050152ae2
        http://127.0.0.1:8888/lab?token=ee9b275d963c5e19632a926bd8117683f5fa36d050152ae2
[I 2023-07-03 18:29:15.618 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2023-07-03 18:29:18.653 LabApp] The extension "neptune-notebooks" is outdated.
    
[I 2023-07-03 18:29:18.653 LabApp] Build is up to date
[I 2023-07-03 18:30:03.277 ServerApp] Kernel started: 1b8baf5e-1331-4a17-8b6f-444de62ea208
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2023-07-03 18:30:03.735 ServerApp] Connecting to kernel 1b8baf5e-1331-4a17-8b6f-444de62ea208.
[I 2023-07-03 18:30:03.736 ServerApp] Connecting to kernel 1b8baf5e-1331-4a17-8b6f-444de62ea208.
[I 2023-07-03 18:30:03.737 ServerApp] Connecting to kernel 1b8baf5e-1331-4a17-8b6f-444de62ea208.
[I 2023-07-03 18:46:21.796 LabApp] 302 GET /lab (@127.0.0.1) 2.28ms
[W 2023-07-03 18:46:21.898 ServerApp] 404 GET /apple-touch-icon-precomposed.png (@127.0.0.1) 23.23ms referer=None
[W 2023-07-03 18:46:21.900 ServerApp] 404 GET /apple-touch-icon.png (@127.0.0.1) 0.74ms referer=None
[W 2023-07-03 18:46:27.096 ServerApp] 401 POST /login?next=%2Flab (@127.0.0.1) 2.30ms referer=http://127.0.0.1:8888/login?next=%2Flab
[I 2023-07-03 19:10:17.450 ServerApp] Starting buffering for 1b8baf5e-1331-4a17-8b6f-444de62ea208:05743d6c-6a80-4b51-9022-94a9cd80f015
```

also when I use `jupyter labextension install neptune-notebooks` command, there are warnings:`UserWarning: ValueError: The extension "neptune-notebooks" does not yet support the current version of JupyterLab.`

here are my software version:
```
macos 13.4.1
Python 3.11.4
jupyterlab  4.0.2
```

**Comment by SiddhantSadangi** [comment] 2023-07-03 11:54
Thanks for sharing the details 🙏 

Can you also share the version of `neptune` or `neptune-client` that you are using?

**Comment by SiddhantSadangi** [comment] 2023-07-03 12:06
I was able to reproduce the issue with `jupyterlab==4.0.2`.

Looks like the widget does not support `jupyterlab>=4.0`. Will it be possible for you to downgrade to `juyterlab<4.0`?

Please let me know if this works 🙏

**Comment by GuangShuaiWang** [comment] 2023-07-03 12:10
okok, thanks.  I will try it tomorrow.😃😃

**Comment by GuangShuaiWang** [comment] 2023-07-04 02:22
It works!!! @SiddhantSadangi 

when I use the `jupyterlab==3.65`, this problem does't come out. "Build Recommended" notification can be find when I use "jupyter lab" command.

**Comment by SiddhantSadangi** [comment] 2023-07-04 09:40
That's great to hear 🎉 

I will keep this issue open till we do not add support for `jupyterlab>=4.0`. 

If you have any questions/suggestions about `neptune-notebooks`, feel free to put those here, or open a new issue if there's anything else I can help you with 🤗 

Until then, have a great day 🌞

**Comment by SiddhantSadangi** [comment] 2024-05-13 16:01
I'm closing this as our Jupyter integration has been deprecated, and we don't intend to update the widget to support newer versions of JupyterLab in the foreseeable future.

**Closed by SiddhantSadangi** 2024-05-13 16:01 UTC
Labels: bug
